name: CI
on: [push, pull_request]
jobs:
  cs-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          extensions: mbstring, fileinfo, json, intl, dom
          tools: php-cs-fixer:2.16.3, composer:v1
      - name: install
        run: cd project && composer install
      - name: 'php-cs-fixer check'
        run: cd project && vendor/bin/php-cs-fixer fix --dry-run --diff
